Added additional validation for connectivity checks.
csiro-coasts/emsarray pull request #168
Opened 2024-12-16 07:38 UTC by david-sh-csiro

2025-01-08 03:23 UTC, mx-moth requested changes

2025-01-08 03:23 UTC, mx-moth commented on src/emsarray/conventions/ugrid.py
> +            return True
Because of the nature of check functions like this, an early return of `True` can lead to bugs in the future. If another developer comes along and adds another check below this check - just as you've added a check below the existing checks - then that new check will be skipped if there is a missing `_FillValue`. An early return of `False` is always valid as any failed check renders the whole connectivity array invalid. Consider instead:

```python
if '_FillValue' in data_array.encoding:
    fill_value = data_array.encoding['_FillValue']
    ...
    if lower_bound < fill_value < upper_bound:
        warnings.warn(...)
        return False

return True
```

2025-01-08 03:23 UTC, mx-moth commented on src/emsarray/conventions/ugrid.py
> +            return False
This shouldn't be checked. The theoretical upper bound is a conservative over estimate, useful when computing our own _FillValue as a value that is guaranteed never to collide. However in practice lower values can safely be used as long as the actual _FillValue is lower than actual upper bound. This test will give superfluous warnings on valid data sets.

2025-01-08 03:23 UTC, mx-moth commented on src/emsarray/conventions/ugrid.py
> +        actual_upper_bound = numpy.nanmax(data_array)
The maximum edge ID can be found more precisely with 

```python
upper_bound = self.edge_count + lower_bound
```

Because of the exact issue of variables being incorrectly masked and therefore missing valid data, any information gleaned by introspecting the data is potentially suspect. This check as written would fail if `_FillValue` was exactly the maximum edge ID. `numpy.nanmax()` would not find this value as it has been masked, returning the second-to-last value which would then incorrectly cause the checks below to pass.

2025-01-08 03:23 UTC, mx-moth commented on src/emsarray/conventions/ugrid.py
> +        if lower_bound < fill_value < actual_upper_bound:
These should be less than or equal checks. A fill value of 0 and a lower bound of 0 is invalid as it will mask out the first edge ID:

```python
if lower_bound <= fill_value <= upper_bound:
```

2025-01-21 01:04 UTC, david-sh-csiro commented on src/emsarray/conventions/ugrid.py
> +            return True
Updated to match example.

2025-01-21 01:04 UTC, david-sh-csiro commented on src/emsarray/conventions/ugrid.py
> +            return False
Removed theoretical upper bound check.

2025-01-21 01:05 UTC, david-sh-csiro commented on src/emsarray/conventions/ugrid.py
> +        actual_upper_bound = numpy.nanmax(data_array)
Updated to use better way of calculating upper bound.

2025-01-21 01:05 UTC, david-sh-csiro commented on src/emsarray/conventions/ugrid.py
> +        if lower_bound < fill_value < actual_upper_bound:
Updated boundary checks and added unit tests to validate boundaries.

2025-01-21 01:14 UTC, mx-moth approved these changes
Looks good!

2025-01-21 03:15 UTC, merged